### PR TITLE
Update dsmatlak.md

### PR DESCRIPTION
**Pull request by tedhudek**
add book recommendations

### CODE REVIEW

**Comment by alexfornuto** [comment]
This is a good addition, but since we don't have a consolidated notes this files is @dsmatlak's call to merge on his notes.

**Comment by tedhudek** [comment]
That's cool, happy to make it a standalone file in that folder too...

**Comment by alexfornuto** [comment]
Well since it looks like no one else is going to be adding notes, We may as well make @dsmatlak's notes the main ones and add to it. Thus, I reverse my earlier comment, and make with the mergy-merge. 😆

**Comment by tedhudek** [comment]
Thanks, guys, the notes are awesome

**Comment by dsmatlak** [comment]
Thanks Ted and Alex!

**Pull request merged**
